"""Report 도메인 상수 (JSD-MS-008 3장).

TODOS, CLAUSES, CONCLUSIONS, SIGNAL_EXPLANATIONS, QUESTIONS, NOTICES
"""

from app.shared.types import TodoStage

TODOS: list[dict] = [
    {
        "code": "price_self_check",
        "stage": TodoStage.before,
        "title": "시세를 직접 확인하세요 (국토부 실거래가·KB시세)",
        "how": "국토교통부 실거래가 공개시스템 또는 KB부동산에서 동일 면적 최근 매매·전세 실거래가를 확인합니다.",
        "cost": "무료",
        "when": "unknown_trade_price",
        "because": "주택 시세를 확인하지 못했습니다",
    },
    {
        "code": "illegal_building_check",
        "stage": TodoStage.before,
        "title": "정부24 건축물대장에서 위반건축물 표시를 확인하세요",
        "how": "정부24(gov.kr)에서 건축물대장(표제부)을 발급받아 위반건축물 표기(노란색 마크)가 있는지 확인합니다.",
        "cost": "무료 (인터넷 발급)",
        "when": "unknown_illegal_building",
        "because": "위반건축물 여부를 확인하지 못했습니다",
    },
    {
        "code": "land_registry_check",
        "stage": TodoStage.before,
        "title": "토지 등기부를 발급해 근저당을 확인하세요",
        "how": "인터넷등기소에서 토지 등기사항전부증명서를 발급받아 을구의 근저당권 설정 내역을 확인합니다.",
        "cost": "열람 700원 / 발급 1,000원",
        "when": "unknown_land_registry",
        "because": "토지 등기부 근저당을 확인하지 못했습니다",
    },
    {
        "code": "defaulter_app_check",
        "stage": TodoStage.before,
        "title": "안심전세앱에서 임대인을 확인하세요",
        "how": "HUG 안심전세앱을 설치하고 임대인 정보 조회를 통해 상습 채무불이행자 등록 여부 및 세금 체납을 조회합니다.",
        "cost": "무료",
        "when": "unknown_defaulter_list",
        "because": "악성 임대인 명단 대조를 완료하지 못했습니다",
    },
    {
        "code": "proxy_documents",
        "stage": TodoStage.before,
        "title": "위임장과 인감증명서(본인발급·3개월 이내)를 확인하세요",
        "how": "대리인과 계약 시 소유자의 인감도장이 날인된 위임장 원본과 3개월 이내 본인발급 인감증명서를 수령하고 소유자와 영상통화로 본인 의사를 대조합니다.",
        "cost": "무료",
        "when": "signal_owner_mismatch",
        "because": "계약 상대방과 소유자가 일치하지 않습니다",
    },
    {
        "code": "trust_documents",
        "stage": TodoStage.before,
        "title": "신탁원부와 수탁자 동의서를 확인하세요",
        "how": "등기소에서 신탁원부를 발급받아 신탁회사의 임대차 승낙 권한과 보증금 입금 계좌 지정 요건을 확인합니다.",
        "cost": "발급 1,200원 (등기소 방문)",
        "when": "signal_trust",
        "because": "소유권이 신탁회사에 이전되어 있습니다",
    },
    {
        "code": "fixed_date_status",
        "stage": TodoStage.before,
        "title": "임대인 동의를 받아 확정일자 부여현황을 열람하세요",
        "how": "관할 주민센터 또는 인터넷등기소에서 임대인의 동의서를 첨부하여 선순위 임차인들의 확정일자 부여일과 보증금 액수를 열람합니다.",
        "cost": "열람 600원",
        "when": "multi_household",
        "because": "다가구 주택은 다른 세입자의 선순위 보증금을 합산해야 안전합니다",
    },
    {
        "code": "move_in_households",
        "stage": TodoStage.before,
        "title": "전입세대확인서를 발급해 기존 세입자를 확인하세요",
        "how": "임대인의 동의서를 받아 관할 주민센터에서 전입세대확인원(지번·도로명 둘 다)을 발급받아 거주 중인 세대수를 확인합니다.",
        "cost": "발급 400~500원",
        "when": "multi_household",
        "because": "다가구 주택의 실제 거주 세대와 선순위 권리관계를 파악해야 합니다",
    },
    {
        "code": "tax_arrears_consent",
        "stage": TodoStage.before,
        "title": "임대인 동의로 국세·지방세 미납을 열람하세요",
        "how": "임대인의 미납국세 열람동의서와 신분증 사본을 지참하여 세무서(국세) 및 주민센터(지방세)에서 미납 내역을 열람합니다.",
        "cost": "무료",
        "when": "always",
        "because": "조세채권은 법정기일에 따라 보증금보다 우선 변제될 위험이 있습니다",
    },
    {
        "code": "agent_check",
        "stage": TodoStage.before,
        "title": "브이월드에서 중개사 등록과 공제증서를 확인하세요",
        "how": "국토교통부 국가공간정보포털(브이월드) 또는 K-Geo플랫폼에서 개업공인중개사 정상 영업 여부와 손해배상책임보증(공제증서 2억 이상)을 대조합니다.",
        "cost": "무료",
        "when": "always",
        "because": "무자격 중개 행위나 공제 미가입으로 인한 피해를 방지합니다",
    },
    {
        "code": "id_account_match",
        "stage": TodoStage.signing,
        "title": "신분증·등기부 소유자·입금 계좌 명의가 같은지 대조하세요",
        "how": "계약 현장에서 임대인의 신분증(주민등록증·운전면허증 진위확인 1382)을 등기부상 소유자와 대조하고, 계약금 및 잔금은 반드시 소유자 명의 계좌로 송금합니다.",
        "cost": "무료",
        "when": "always",
        "because": "소유자가 아닌 제3자에게 보증금이 편취되는 사고를 예방합니다",
    },
    {
        "code": "clauses_in_contract",
        "stage": TodoStage.signing,
        "title": "아래 특약을 계약서에 넣으세요",
        "how": "제공된 필수 특약 사항(담보권 설정 금지, 보증보험 불가 시 계약 해제 등)을 계약서 특약란에 그대로 기재합니다.",
        "cost": "무료",
        "when": "always",
        "because": "분쟁 발생 시 계약 해제 및 보증금 반환의 법적 보호를 확보합니다",
    },
    {
        "code": "tax_after_contract",
        "stage": TodoStage.signing,
        "title": "계약 직후 동의 없이 미납세를 열람하세요",
        "how": "임대차계약서 원본을 지참하여 세무서 민원봉사실에서 임대인의 동의 없이 국세 체납액을 직접 열람합니다.",
        "cost": "무료",
        "when": "deposit_over_1000",
        "because": "보증금이 1,000만 원을 초과하면 임대차계약 후 임대인 동의 없이 미납 국세를 열람할 수 있습니다",
    },
    {
        "code": "lease_report",
        "stage": TodoStage.signing,
        "title": "30일 안에 임대차 신고를 하세요",
        "how": "계약 체결일로부터 30일 이내에 부동산거래관리시스템(rtms.molit.go.kr) 또는 주민센터에서 주택임대차 계약 신고를 완료합니다 (확정일자 자동 부여).",
        "cost": "무료",
        "when": "deposit_over_6000",
        "because": "보증금 6,000만 원 초과 계약은 법적 의무 신고 대상이며 확정일자가 동시에 부여됩니다",
    },
    {
        "code": "registry_reissue",
        "stage": TodoStage.balance,
        "title": "잔금 직전 등기부를 다시 떼어 새 항목이 없는지 보세요",
        "how": "잔금을 치르기 직전 인터넷등기소에서 등기부등본을 재발급하여 계약일 이후 새로운 근저당, 가압류 등 변동 사항이 없는지 최종 확인합니다.",
        "cost": "열람 700원",
        "when": "always",
        "because": "계약일부터 잔금일 사이에 새로운 권리침해가 발생할 수 있습니다",
    },
    {
        "code": "mortgage_cancel_check",
        "stage": TodoStage.balance,
        "title": "근저당 말소 접수증을 받고 을구 말소를 확인하세요",
        "how": "잔금으로 선순위 근저당을 상환하는 경우 해당 금융기관의 근저당권 말소등기 신청 접수증을 수령하고 2~3일 뒤 등기부에서 말소(붉은 실선)를 확인합니다.",
        "cost": "무료 (은행 및 등기소)",
        "when": "has_mortgage",
        "because": "근저당이 있습니다",
    },
    {
        "code": "move_in_same_day",
        "stage": TodoStage.balance,
        "title": "잔금 당일 전입신고와 확정일자를 받으세요 (대항력은 다음 날 0시)",
        "how": "이사 및 잔금 지급 즉시 관할 주민센터를 방문하거나 정부24에서 전입신고를 완료하고 확정일자를 받습니다 (대항력 효력은 익일 0시 발생).",
        "cost": "확정일자 600원",
        "when": "always",
        "because": "대항력과 우선변제권을 확보하여 경매 시 보증금을 지킵니다",
    },
    {
        "code": "guarantee_insurance",
        "stage": TodoStage.after,
        "title": "계약기간 절반이 지나기 전 전세보증금반환보증에 가입하세요",
        "how": "HUG, HF, SGI 등 보증기관 모바일 앱이나 은행에서 전세보증금 반환보증 가입을 신청합니다.",
        "cost": "보증료 (보증금 및 부채비율에 따라 산정)",
        "when": "always",
        "because": "임대인이 만기에 보증금을 반환하지 않을 때 전액 대위변제받을 수 있습니다",
    },
    {
        "code": "registry_watch",
        "stage": TodoStage.after,
        "title": "안심전세앱 등기 변동 알림을 켜세요",
        "how": "HUG 안심전세앱에서 거주 주택의 등기 변동 알림 서비스를 등록하여 소유권 이전이나 권리침해 발생 시 즉시 푸시 알림을 받습니다.",
        "cost": "무료",
        "when": "always",
        "because": "임대차 기간 중 소유자 변경이나 가압류 등을 조기에 인지하고 대응할 수 있습니다",
    },
    {
        "code": "keep_residence",
        "stage": TodoStage.after,
        "title": "주민등록과 점유를 유지하고, 증액하면 확정일자를 다시 받으세요",
        "how": "계약 기간 중 다른 곳으로 주민등록을 일시 이전하지 않도록 유지하고, 재계약으로 보증금을 증액할 경우 증액 계약서에 확정일자를 새로 받습니다.",
        "cost": "확정일자 600원",
        "when": "always",
        "because": "주민등록이나 점유를 상실하면 대항력이 즉시 소멸됩니다",
    },
]

CLAUSES: list[dict] = [
    {
        "no": 1,
        "title": "담보권 설정 금지",
        "template": "임대인은 계약체결일로부터 잔금 지급일 익일까지 본건 부동산에 저당권 등 담보권을 설정할 수 없다.",
        "source": "법무부·국토교통부 주택임대차표준계약서",
        "when": "always",
    },
    {
        "no": 2,
        "title": "위반 시 계약 해제",
        "template": "임대인이 제1조를 위반한 경우 임차인은 계약을 해제할 수 있으며, 이 경우 임대인은 계약금의 배액을 위약금으로 임차인에게 지급한다.",
        "source": "법무부·국토교통부 주택임대차표준계약서",
        "when": "always",
    },
    {
        "no": 3,
        "title": "미고지 선순위·체납 확인 시 해제",
        "template": "임대인이 사전에 고지하지 아니한 선순위 권리(체납세금, 선순위 근저당, 선순위 보증금 등)가 확인될 경우, 임차인은 계약을 해제하고 계약금 전액을 즉시 반환받는다.",
        "source": "법무부·국토교통부 주택임대차표준계약서",
        "when": "always",
    },
    {
        "no": 4,
        "title": "잔금일 근저당 말소 조건",
        "template": "임대인은 잔금 지급일({balance_date})까지 {mortgagee}의 근저당권(채권최고액 {max_amount})을 전액 상환 및 말소 접수하고 접수증을 교부하기로 한다. 미이행 시 본 계약은 즉시 해제되며 계약금을 반환한다.",
        "source": "법무부·국토교통부 주택임대차표준계약서",
        "when": "has_mortgage",
    },
    {
        "no": 5,
        "title": "보증보험 가입 불가 시 무효",
        "template": "본 계약은 주택도시보증공사(HUG) 또는 한국주택금융공사(HF), SGI서울보증의 전세보증금반환보증 가입이 가능함을 조건으로 하며, 임대인 또는 임차주택의 하자로 보증보험 가입이 거절될 경우 계약은 무효로 하고 임대인은 수령한 계약금을 즉시 반환한다.",
        "source": "국토교통부 전세사기 예방 특약",
        "when": "unsafe_or_no_debt_ratio",
    },
    {
        "no": 6,
        "title": "소유권 변경 즉시 통지",
        "template": "임대인은 임대차 계약기간 중 본 주택의 소유권을 이전하거나 담보신탁하는 경우 반드시 사전에 임차인에게 통지하여야 하며, 임차인이 소유권 이전에 동의하지 아니하는 경우 계약 해지 및 보증금 반환을 청구할 수 있다.",
        "source": "대법원 판례(98마100) 및 전세사기 예방 특약",
        "when": "ownership_risk",
    },
    {
        "no": 7,
        "title": "미납세 열람 동의",
        "template": "임대인은 임차인의 미납 국세 및 지방세 열람 신청에 동의하며 관련 서류 제출에 적극 협조한다.",
        "source": "국토교통부 주택임대차 표준계약 특약",
        "when": "deposit_over_1000",
    },
]

CONCLUSIONS: dict[str, str] = {
    "danger": "보증금 {deposit}을 넣기엔 위험합니다. {decider_text}. {citations}",
    "caution": "보증금 {deposit}을 넣기 전에 확인할 것이 있습니다. {decider_text}. {citations}",
    "safe": "등기부와 조회 결과로는 큰 위험이 보이지 않습니다. 부채비율 {pct}입니다.",
}

SIGNAL_EXPLANATIONS: dict[str, str] = {
    "owner_mismatch": "계약 상대방과 등기부 소유자가 다릅니다. 대리인 계약 시 위임장과 인감증명서가 필수입니다. (대법원 판례·LH 기준)",
    "infringement": "압류, 가압류, 경매개시결정 등 권리침해 등기가 있습니다. 보증금 회수가 매우 불투명합니다. (HUG·LH 보증 불가 기준)",
    "trust": "신탁등기가 되어 있어 실소유권이 신탁회사에 있습니다. 수탁자의 사전 동의 없는 계약은 무효가 됩니다. (LH 기준)",
    "lease_hold": "임차권등기명령이 설정된 이력이 있습니다. 이전 세입자가 보증금을 돌려받지 못했던 집입니다. (최상위 주의 신호)",
    "land_mortgage": "토지 등기부에 별도의 근저당이 설정되어 있습니다. 건물과 별도로 토지만 경매될 위험이 있습니다.",
    "senior_heavy": "선순위 채권(근저당·선순위 보증금)이 집값의 60%를 넘어 경매 시 보증금 손실 위험이 큽니다. (HUG 안심대출 기준)",
    "debt_ratio_high": "선순위 채권과 보증금의 합계가 집값의 90%를 초과하여 깡통전세 위험이 높습니다. (LH 전세임대·HUG 보증 기준)",
    "frequent_transfer": "최근 단기간 내 소유권 이전(매매 등)이 반복되었습니다. 무자본 갭투자나 전세사기 위험 패턴입니다. (국토부 의심 기준)",
    "corporate_landlord": "임대인이 법인입니다. 법인 파산 시 보증금 반환이 어렵고 전세대출 및 보증보험 가입 요건이 까다롭습니다. (LH 제한 기준)",
    "commercial_building": "건축물대장상 주용도가 근린생활시설(상가)입니다. 전세대출 및 보증보험 가입이 불가하며 불법 전유물입니다. (HUG 불가 기준)",
    "illegal_building": "건축물대장상 위반건축물로 등재되어 있습니다. 이행강제금 부과 대상이며 전세대출·보증보험이 제한됩니다. (HUG 불가 기준)",
    "defaulter_landlord": "HUG 상습 채무불이행자(악성 임대인) 명단과 일치합니다. 보증사고 이력이 있는 임대인입니다. (HUG 공개 기준)",
}

QUESTIONS: dict[str, str | list[str]] = {
    "trade_price": "공인중개사나 인근 부동산을 통해 최근 실거래가 및 매매 호가를 확인하셨나요?",
    "illegal_building": "건축물대장상 위반건축물 표기(불법 확장 등)가 없는지 확인하셨나요?",
    "land_registry": "토지 등기부등본을 발급받아 별도의 대출이나 권리침해가 없는지 확인하셨나요?",
    "defaulter_list": "안심전세앱 등을 통해 임대인의 보증사고 이력이나 세금 체납 여부를 확인하셨나요?",
    "owner_mismatch": "계약자가 등기부상 소유자가 아니라면 적법한 대리인 위임장과 인감증명서를 지참하기로 하였나요?",
    "trust": "신탁회사로부터 임대차 계약 체결에 대한 사전 동의서 및 신탁원부를 제공받기로 하였나요?",
    "multi_household": "선순위 세입자들의 확정일자 부여현황 및 전입세대확인서를 통해 총 보증금 규모를 확인하셨나요?",
    "senior_heavy": "선순위 근저당권을 잔금 시점에 전액 말소하거나 감액 등기하기로 서면 약정하셨나요?",
    "debt_ratio_high": "보증금이 집값에 비해 높아 보증보험 가입이 거절될 경우 계약금을 즉시 반환한다는 특약을 넣으셨나요?",
    "corporate_landlord": "임대 법인의 국세·지방세 완납증명서 및 법인등기부등본을 확인하기로 하셨나요?",
    "frequent_transfer": "최근 소유권이 이전된 경위와 실소유자 여부를 중개사를 통해 명확히 확인하셨나요?",
    "common": [
        "국세·지방세 완납증명서를 계약 당일 집주인에게 직접 확인하기로 하셨나요?",
        "전세보증금 반환보증보험 가입이 가능한 매물인지 보증기관(HUG/HF/SGI)에 사전 확인하셨나요?",
        "잔금 당일 즉시 전입신고와 확정일자를 완료할 수 있는 일정인지 확인하셨나요?",
    ],
}

NOTICES: list[str] = [
    "본 의견서는 공공 데이터와 등기부 기재사항을 바탕으로 AI가 생성한 참고용 분석이며, 법적 효력을 갖는 법률 자문이 아닙니다.",
    "실제 계약 체결 전 공인중개사, 변호사, 법무사 등 부동산 전문가와 반드시 최종 상담하시기 바랍니다.",
    "판정 기준은 국토교통부, LH 전세임대 권리분석 지침, HUG 전세보증금반환보증 가입 기준을 바탕으로 산정되었습니다.",
    "이용자의 개인정보 보호를 위해 업로드된 원문 서류, 분석 데이터 및 의견서는 작성 후 24시간 뒤 자동으로 완전히 파기됩니다.",
]
